///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductResModelData {
/*
{
  "title": "nas",
  "title_ar": "سس",
  "price": "50.00",
  "starting_at": "1997-05-13 00:00:00",
  "ending_at": "2020-05-13 00:00:00",
  "photo": "157424741737764.jpg",
  "description": "asdsadssdasd",
  "description_ar": "asdasda",
  "shop_id": 1,
  "updated_at": "2021-01-11 17:00:22",
  "created_at": "2021-01-11 17:00:22",
  "id": 12,
  "available": false,
  "photo_url": "http://40.76.71.25/v1region/157424741737764.jpg"
} 
*/

  String title;
  String titleAr;
  String price;
  String startingAt;
  String endingAt;
  String photo;
  String description;
  String descriptionAr;
  int shopId;
  String updatedAt;
  String createdAt;
  int id;
  bool available;
  String photoUrl;

  ProductResModelData({
    this.title,
    this.titleAr,
    this.price,
    this.startingAt,
    this.endingAt,
    this.photo,
    this.description,
    this.descriptionAr,
    this.shopId,
    this.updatedAt,
    this.createdAt,
    this.id,
    this.available,
    this.photoUrl,
  });
  ProductResModelData.fromJson(Map<String, dynamic> json) {
    title = json["title"]?.toString();
    titleAr = json["title_ar"]?.toString();
    price = json["price"]?.toString();
    startingAt = json["starting_at"]?.toString();
    endingAt = json["ending_at"]?.toString();
    photo = json["photo"]?.toString();
    description = json["description"]?.toString();
    descriptionAr = json["description_ar"]?.toString();
    shopId = json["shop_id"]?.toInt();
    updatedAt = json["updated_at"]?.toString();
    createdAt = json["created_at"]?.toString();
    id = json["id"]?.toInt();
    available = json["available"];
    photoUrl = json["photo_url"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["title"] = title;
    data["title_ar"] = titleAr;
    data["price"] = price;
    data["starting_at"] = startingAt;
    data["ending_at"] = endingAt;
    data["photo"] = photo;
    data["description"] = description;
    data["description_ar"] = descriptionAr;
    data["shop_id"] = shopId;
    data["updated_at"] = updatedAt;
    data["created_at"] = createdAt;
    data["id"] = id;
    data["available"] = available;
    data["photo_url"] = photoUrl;
    return data;
  }
}

class ProductResModel {
/*
{
  "status": 1,
  "message": "تم الاضافة بنجاح",
  "data": {
    "title": "nas",
    "title_ar": "سس",
    "price": "50.00",
    "starting_at": "1997-05-13 00:00:00",
    "ending_at": "2020-05-13 00:00:00",
    "photo": "157424741737764.jpg",
    "description": "asdsadssdasd",
    "description_ar": "asdasda",
    "shop_id": 1,
    "updated_at": "2021-01-11 17:00:22",
    "created_at": "2021-01-11 17:00:22",
    "id": 12,
    "available": false,
    "photo_url": "http://40.76.71.25/v1region/157424741737764.jpg"
  }
} 
*/

  int status;
  String message;
  ProductResModelData data;

  ProductResModel({
    this.status,
    this.message,
    this.data,
  });
  ProductResModel.fromJson(Map<String, dynamic> json) {
    status = json["status"]?.toInt();
    message = json["message"]?.toString();
    data = (json["data"] != null)
        ? ProductResModelData.fromJson(json["data"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["status"] = status;
    data["message"] = message;
    if (data != null) {
      data["data"] = this.data.toJson();
    }
    return data;
  }
}
