///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductModelDataData {
/*
{
  "id": 12,
  "shop_id": 1,
  "title": "nas",
  "title_ar": "سس",
  "description": "asdsadssdasd",
  "description_ar": "asdasda",
  "price": "50.00",
  "starting_at": "1997-05-13 00:00:00",
  "ending_at": "2020-05-13 00:00:00",
  "photo": "157424741737764.jpg",
  "created_at": "2021-01-11 17:00:22",
  "updated_at": "2021-01-11 17:00:22",
  "available": false,
  "photo_url": "http://40.76.71.25/v1region/157424741737764.jpg"
} 
*/

  int id;
  int shopId;
  String title;
  String titleAr;
  String description;
  String descriptionAr;
  String price;
  String startingAt;
  String endingAt;
  String photo;
  String createdAt;
  String updatedAt;
  bool available;
  String photoUrl;

  ProductModelDataData({
    this.id,
    this.shopId,
    this.title,
    this.titleAr,
    this.description,
    this.descriptionAr,
    this.price,
    this.startingAt,
    this.endingAt,
    this.photo,
    this.createdAt,
    this.updatedAt,
    this.available,
    this.photoUrl,
  });
  ProductModelDataData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    shopId = json["shop_id"]?.toInt();
    title = json["title"]?.toString();
    titleAr = json["title_ar"]?.toString();
    description = json["description"]?.toString();
    descriptionAr = json["description_ar"]?.toString();
    price = json["price"]?.toString();
    startingAt = json["starting_at"]?.toString();
    endingAt = json["ending_at"]?.toString();
    photo = json["photo"]?.toString();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    available = json["available"];
    photoUrl = json["photo_url"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["shop_id"] = shopId;
    data["title"] = title;
    data["title_ar"] = titleAr;
    data["description"] = description;
    data["description_ar"] = descriptionAr;
    data["price"] = price;
    data["starting_at"] = startingAt;
    data["ending_at"] = endingAt;
    data["photo"] = photo;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["available"] = available;
    data["photo_url"] = photoUrl;
    return data;
  }
}

class ProductModelData {
/*
{
  "current_page": 1,
  "data": [
    {
      "id": 12,
      "shop_id": 1,
      "title": "nas",
      "title_ar": "سس",
      "description": "asdsadssdasd",
      "description_ar": "asdasda",
      "price": "50.00",
      "starting_at": "1997-05-13 00:00:00",
      "ending_at": "2020-05-13 00:00:00",
      "photo": "157424741737764.jpg",
      "created_at": "2021-01-11 17:00:22",
      "updated_at": "2021-01-11 17:00:22",
      "available": false,
      "photo_url": "http://40.76.71.25/v1region/157424741737764.jpg"
    }
  ],
  "first_page_url": "http://40.76.71.25/v1region/api/v1/shop/my-offers?page=1",
  "from": 1,
  "last_page": 1,
  "last_page_url": "http://40.76.71.25/v1region/api/v1/shop/my-offers?page=1",
  "next_page_url": null,
  "path": "http://40.76.71.25/v1region/api/v1/shop/my-offers",
  "per_page": 20,
  "prev_page_url": null,
  "to": 8,
  "total": 8
} 
*/

  int currentPage;
  List<ProductModelDataData> data;
  String firstPageUrl;
  int from;
  int lastPage;
  String lastPageUrl;
  String nextPageUrl;
  String path;
  int perPage;
  String prevPageUrl;
  int to;
  int total;

  ProductModelData({
    this.currentPage,
    this.data,
    this.firstPageUrl,
    this.from,
    this.lastPage,
    this.lastPageUrl,
    this.nextPageUrl,
    this.path,
    this.perPage,
    this.prevPageUrl,
    this.to,
    this.total,
  });
  ProductModelData.fromJson(Map<String, dynamic> json) {
    currentPage = json["current_page"]?.toInt();
    if (json["data"] != null) {
      var v = json["data"];
      var arr0 = List<ProductModelDataData>();
      v.forEach((v) {
        arr0.add(ProductModelDataData.fromJson(v));
      });
      this.data = arr0;
    }
    firstPageUrl = json["first_page_url"]?.toString();
    from = json["from"]?.toInt();
    lastPage = json["last_page"]?.toInt();
    lastPageUrl = json["last_page_url"]?.toString();
    nextPageUrl = json["next_page_url"]?.toString();
    path = json["path"]?.toString();
    perPage = json["per_page"]?.toInt();
    prevPageUrl = json["prev_page_url"]?.toString();
    to = json["to"]?.toInt();
    total = json["total"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["current_page"] = currentPage;
    if (this.data != null) {
      var v = this.data;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data["data"] = arr0;
    }
    data["first_page_url"] = firstPageUrl;
    data["from"] = from;
    data["last_page"] = lastPage;
    data["last_page_url"] = lastPageUrl;
    data["next_page_url"] = nextPageUrl;
    data["path"] = path;
    data["per_page"] = perPage;
    data["prev_page_url"] = prevPageUrl;
    data["to"] = to;
    data["total"] = total;
    return data;
  }
}

class ProductModel {
/*
{
  "status": 1,
  "message": "تم التحميل",
  "data": {
    "current_page": 1,
    "data": [
      {
        "id": 12,
        "shop_id": 1,
        "title": "nas",
        "title_ar": "سس",
        "description": "asdsadssdasd",
        "description_ar": "asdasda",
        "price": "50.00",
        "starting_at": "1997-05-13 00:00:00",
        "ending_at": "2020-05-13 00:00:00",
        "photo": "157424741737764.jpg",
        "created_at": "2021-01-11 17:00:22",
        "updated_at": "2021-01-11 17:00:22",
        "available": false,
        "photo_url": "http://40.76.71.25/v1region/157424741737764.jpg"
      }
    ],
    "first_page_url": "http://40.76.71.25/v1region/api/v1/shop/my-offers?page=1",
    "from": 1,
    "last_page": 1,
    "last_page_url": "http://40.76.71.25/v1region/api/v1/shop/my-offers?page=1",
    "next_page_url": null,
    "path": "http://40.76.71.25/v1region/api/v1/shop/my-offers",
    "per_page": 20,
    "prev_page_url": null,
    "to": 8,
    "total": 8
  }
} 
*/

  int status;
  String message;
  ProductModelData data;

  ProductModel({
    this.status,
    this.message,
    this.data,
  });
  ProductModel.fromJson(Map<String, dynamic> json) {
    status = json["status"]?.toInt();
    message = json["message"]?.toString();
    data =
        (json["data"] != null) ? ProductModelData.fromJson(json["data"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["status"] = status;
    data["message"] = message;
    if (data != null) {
      data["data"] = this.data.toJson();
    }
    return data;
  }
}
